# Generated by Django 3.1.2 on 2020-11-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=255, null=True)),
                ('zip_code', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
